### ISSUE TITLE
pSConfig Debian packages

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/mesh-config#112]
We need to take a look at the dependencies and libraries from https://github.com/perfsonar/mesh-config/issues/75 and https://github.com/perfsonar/mesh-config/issues/74#issuecomment-340574658 and build the Debian package corresponding to #109

**Comment by vvidic** [comment]
psconfig packages available in snapshot repo now.

**Comment by laeti-tia** [comment]
And added to the nightly builds.  I've opened https://github.com/perfsonar/bundles/issues/12 to track addition to the bundle packages.
