### ISSUE TITLE
Documentation needs to be updated

### ISSUE THREAD

**Issue by igarny** [perfsonar/mesh-config#13]
Hi guys,

There is a mistake in the example given on the meshconfig example in the documentation (or at least is not valid any more). Please review the discussion below!

https://github.com/perfsonar/mesh-config/blob/master/doc/example.conf

Best regards,
Ivan

From: Andrew Lake [mailto:andy@es.net] 
Sent: Dienstag, 14. Juli 2015 15:59
To: Garnizov, Ivan (RRZE)
Subject: RE: [perfsonar-user] Lost all Owamp testing on Thursday at 1:00am

Hi Ivan,

That is a mistake in that example. If you are using those settings as well then you will have problems. The toolkit defaults and what we run on ESnet is 10 packets per second (.1) and a sample_count of 600. If you do 100 packets per second (.01), I’d recommend making it 6000 so it works out to every 60 seconds a summary is reported. 

Thanks,
Andy

On Tue, Jul 14, 2015 at 9:54 AM, Garnizov, Ivan (RRZE) ivan.garnizov@fau.de wrote:
Hi Andy,

https://github.com/perfsonar/mesh-config/blob/master/doc/example.conf

```
  <test_spec owamp_test>
  # Define a test spec for doing jitter, loss and latency testing

  type              perfsonarbuoy/owamp  # Perform a constant low-bandwidth OWAMP test
  packet_interval   0.01                 # Send 100 packets every second (i.e. pause 0.01 seconds between each packet)
  loss_threshold    10                   # Wait no more than 10 seconds for a response
  session_count     18000                # Refresh the test every half hour (once every 18000 packets)
  sample_count      300                  # Send results back every 30 seconds (once every 300 packets)
  packet_padding    0                    # The size of the packets (not including the IP/UDP headers)
  bucket_width      0.001                # The granularity of the measurements
</test_spec>
```

**Comment by arlake228** [comment]
Fixed in commit 38a5ea32df0f139110b04d50402fae955ef7cdf2
