### ISSUE TITLE
Explore whether it really makes sense to still use the config_daemon 

### ISSUE THREAD

**Issue by arlake228** [perfsonar/mesh-config#17]
Right now if you have use_toolkit set to 1 it uses the config_dameon to save files and restart services. I am not sure this is entirely necessary. it probably makes sense for things like the toolkit web UI but for the meshconfig I am less sure, especially since it runs on many hosts without the toolkit just fine (though they do have to install a cron job to restart things that itw ould be nice to drop). We should explore dropping "use_toolkit" altogether.

**Comment by apertome** [comment]
At the very least the default/example config could have it set to 0. Don't know what the "default" is currently.

**Comment by arlake228** [comment]
Config daemon is no longer used, closing.
