### ISSUE TITLE
Debian version of generate_configuration can't find BWCTL2.pm

### ISSUE THREAD

**Issue by arlake228** [perfsonar/mesh-config#18]
When trying to run /usr/lib/perfsonar/bin/generate_configuration of 3.5~8.rc2-3 I get the following: 

Can't locate perfSONAR_PS/RegularTesting/Tests/Bwctl2.pm in @INC (@INC contains: /usr/lib/perfsonar/bin/../lib /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /usr/share/perl5/perfSONAR_PS/MeshConfig/Generators/perfSONARRegularTesting.pm line 26.
BEGIN failed--compilation aborted at /usr/share/perl5/perfSONAR_PS/MeshConfig/Generators/perfSONARRegularTesting.pm line 26.
Compilation failed in require at /usr/share/perl5/perfSONAR_PS/MeshConfig/Agent.pm line 27.
BEGIN failed--compilation aborted at /usr/share/perl5/perfSONAR_PS/MeshConfig/Agent.pm line 27.
Compilation failed in require at /usr/lib/perfsonar/bin/generate_configuration line 15.
BEGIN failed--compilation aborted at /usr/lib/perfsonar/bin/generate_configuration line 15.

Looks like more stuff from perl-shared to be pulled-in.

**Comment by laeti-tia** [comment]
Something looks fishy...  Which version of libperfsonar-perl is installed?  Can you give me the output of `aptitude show libperfsonar-perl` ?

**Comment by arlake228** [comment]
See perfsonar/ls-registration-daemon#11
