### ISSUE TITLE
no_agent under member attribute is not accepted by generate_configuration

### ISSUE THREAD

**Issue by soichih** [perfsonar/mesh-config#23]
I have following in my generated mesh config.

```
members: {
type: "mesh",
members: [
"ps1.ochep.ou.edu",
"ps2.ochep.ou.edu"
],
no_agent: [
"ps-02.lnl.infn.it",
"perfsonar2.mi.infn.it",
"perfsonar2.pi.infn.it",
"perfsonar-ps.cnaf.infn.it"
]
},
```

When I run generate_configuration, I get following error message.

```
2015/11/20 11:33:46 (19079) ERROR> Utils.pm:80 perfSONAR_PS::MeshConfig::Utils::load_mesh - Invalid mesh configuration: Unknown attribute: no_agent at /opt/perfsonar_ps/mesh_config/bin/../lib/perfSONAR_PS/MeshConfig/Config/Base.pm line 172.
2015/11/20 11:33:46 (19079) ERROR> Agent.pm:312 perfSONAR_PS::MeshConfig::Agent::__configure_host - Problem with mesh configuration: Invalid mesh configuration: Unknown attribute: no_agent at /opt/perfsonar_ps/mesh_config/bin/../lib/perfSONAR_PS/MeshConfig/Config/Base.pm line 172.
```

Is no_agent under member no longer supported? (http://docs.perfsonar.net/config_mesh.html#config-mesh-group-no-agent)

**Comment by HakanCalimFau** [comment]
Hi,

there is a syntax failure  in the definition. The parameter no_agent is used in the normal config like this:
<group devel_hosts>
  type              mesh

  no_agent          192.168.100.10
  member            192.168.100.11
  member           192.168.100.12
</group>

You try to use the definition in JSON. This will look like this:
{
         "members" : {
            "members" : [
               "192.168.100.11",
               "192.168.100.12"
            ],
            "no_agents" : [
               "192.168.100.10"
            ],
            "type" : "mesh"
         },

In JSON you should use: no_agents! You can write your configuration file as described on the page you have mentioned above. Then use the tool build_json, it is a part of mesh config package, to convert it to  JSON.

Best regards,
Hakan

**Comment by arlake228** [comment]
Nothing to do here, see Hakan's response. In JSON this is no_agents.
