### ISSUE TITLE
meshconfig and pscheduler task throughput --bandwidth

### ISSUE THREAD

**Issue by igarny** [perfsonar/mesh-config#28]
Dear pS Dev,

Based on the documentation here http://docs.perfsonar.net/release_candidates/4.0rc1/config_mesh.html, it appears that the bandwidth parameter is supported only for UDP tests.

I have verified, that pscheduler is able to limit the throughput test with the --bandwidth parameter. 
psc task throughput --omit PT2S --duration PT12S --source pertmp01 --ip-version 4 --dest pertmp02 --bandwidth 1G --parallel 1

Still I do not see a way I can apply this limitation through a central mesh configuration, but is requested by GEANT.

Please consider an implementation in meshconfig for this feature.

Regards,
Ivan

**Comment by arlake228** [comment]
Marking as 4.0, this should be easy to do and we should do this.

**Comment by arlake228** [comment]
Fixed in commit 496118f51d041aa4f3ff9743125f732e60d78b67
