### ISSUE TITLE
FEAT: "500 INTERNAL SERVER ERROR: Until must be in the future"

### ISSUE THREAD

**Issue by igarny** [perfsonar/mesh-config#30]
Hi Andy,

Apart from the obvious problem with the inability to match the host in the mesh, there is another problem, which results in strange error messages.

2016/10/17 16:07:19 (23742) ERROR> Agent.pm:348 perfSONAR_PS::MeshConfig::Agent::__configure_host - Can't find any host blocks associated with the addresses on this machine: 10.0.172.16, pertmp01, 2001:620:5ca1:2f0:f816:3eff:fecb:8f1c
2016/10/17 16:07:39 (23742) WARN> perfsonar_meshconfig_agent:381 main:: - Problem deleting test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Until must be in the future.
CONTEXT:  SQL statement "UPDATE task SET enabled = FALSE WHERE uuid = task_uuid"
PL/pgSQL function api_task_disable(uuid,text) line 19 at SQL statement

Regards,
Ivan

**Comment by arlake228** [comment]
You can ignore that last message, hence it being at the WARN level. The mesh-config is trying to disable a test that has already reached its end-time (meaning its not running anyways) and pscheduler throws that error. I can look at making it less noisy, but it won't cause any problems for you.

**Comment by szymontrocha** [comment]
To confirm there is something wrong - I have seen similar mesage shown freqently in the log in my fresh host too (and wondering what's the problem):

Oct 18 08:50:33 localhost journal: pscheduler-api ERROR    Exception: InternalError: Until must be in the future.#012CONTEXT:  SQL statement "UPDATE task SE
T enabled = FALSE WHERE uuid = task_uuid"#012PL/pgSQL function api_task_disable(uuid,text) line 19 at SQL statement#012#012Traceback (most recent call last)
:#012  File "./pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012InternalError: Until must be in the future.#012CONTEXT:  SQL statement "UPDAT
E task SET enabled = FALSE WHERE uuid = task_uuid"#012PL/pgSQL function api_task_disable(uuid,text) line 19 at SQL statement
Oct 18 08:50:33 localhost journal: pscheduler-api ERROR    Exception: InternalError: Until must be in the future.#012CONTEXT:  SQL statement "UPDATE task SE
T enabled = FALSE WHERE uuid = task_uuid"#012PL/pgSQL function api_task_disable(uuid,text) line 19 at SQL statement#012#012Traceback (most recent call last)
:#012  File "./pschedulerapiserver/dbcursor.py", line 97, in dbcursor_query#012InternalError: Until must be in the future.#012CONTEXT:  SQL statement "UPDAT
E task SET enabled = FALSE WHERE uuid = task_uuid"#012PL/pgSQL function api_task_disable(uuid,text) line 19 at SQL statement
Oct 18 08:50:33 localhost journal: pscheduler-api ERROR    Response 500: Until must be in the future.#012CONTEXT:  SQL statement "UPDATE task SET enabled =
FALSE WHERE uuid = task_uuid"#012PL/pgSQL function api_task_disable(uuid,text) line 19 at SQL statement
Oct 18 08:50:33 localhost journal: pscheduler-api ERROR    Response 500: Until must be in the future.#012CONTEXT:  SQL statement "UPDATE task SET enabled =
FALSE WHERE uuid = task_uuid"#012PL/pgSQL function api_task_disable(uuid,text) line 19 at SQL statement

**Comment by szymontrocha** [comment]
My host is not participating in any mesh. It just runs two regular tests

**Comment by igarny** [comment]
@szymontrocha 
Your messages are not related to meshconfig. Your messages most likely come from the syslog.
These are pscheduler messages.
Not that I know what is wrong there, I am just saying it is likely not related.

**Comment by igarny** [comment]
@arlake228 
I have found the problem and have found that the ERROR message is quite helpful.
I would suggest that this exact WARN message is taken off from the INFO class of messages.
Changing type of issue to feature request

**Comment by szymontrocha** [comment]
What is the reason for this error message? Are you saying this is not an error in fact? Independently of where the meesage coms from it says the same "Until must be in the future" and is marked as an error in the log.

**Comment by mfeit-internet2** [comment]
The error message is an internal problem in pScheduler.  I'll fix that today.

(Fixed in 9ff84996a29d94ad5cd1c07691f1147bbc8d0663 in pscheduler).

**Comment by arlake228** [comment]
Closing since it was fixed in pscheduler.
