### ISSUE TITLE
BUG: duplication of the test declaration for latency tests 

### ISSUE THREAD

**Issue by igarny** [perfsonar/mesh-config#32]
In the text below search for "description   IPv4 owd matrix" to see the duplication (at the bottom).
I start with the steps to replicate the case.

[root@pertmp01 ~]# curl -k https://pertcs01/trainmesh.json
{
   "administrators" : [
      {
         "email" : "ivan.garnizov@fau.de",
         "name" : "Ivan Garnizov"
      },
      {
         "email" : "antoine.delvaux@man.poznan.pl",
         "name" : "Antoine Delvaux"
      }
   ],
   "organizations" : [
      {
         "sites" : [
            {
               "hosts" : [
                  {
                     "addresses" : [
                        "pertmp01.switch.ch",
                        "pertmp04.switch.ch"
                     ]
                  }
               ],
               "location" : {
                  "city" : "Amsterdam"
               }
            },
            {
               "hosts" : [
                  {
                     "addresses" : [
                        "pertmp02.switch.ch"
                     ]
                  }
               ],
               "location" : {
                  "city" : "Frankfurt"
               }
            },
            {
               "hosts" : [
                  {
                     "addresses" : [
                        "pertmp06.switch.ch",
                        "pertmp06.switch.ch"
                     ]
                  }
               ],
               "location" : {
                  "city" : "London"
               }
            }
         ],
         "measurement_archives" : [
            {
               "read_url" : "http://pertcs01.switch.ch/esmond/perfsonar/archive/",
               "type" : "perfsonarbuoy/bwctl"
            },
            {
               "read_url" : "http://pertcs01.switch.ch/esmond/perfsonar/archive/",
               "type" : "perfsonarbuoy/owamp"
            },
            {
               "read_url" : "http://pertcs01.switch.ch/esmond/perfsonar/archive/",
               "type" : "traceroute"
            },
            {
               "read_url" : "http://pertcs01.switch.ch/esmond/perfsonar/archive/",
               "type" : "pinger"
            }
         ],
         "description" : "eduPERT"
      }
   ],
   "tests" : [
      {
         "members" : {
            "members" : [
               "pertmp01.switch.ch",
               "pertmp06.switch.ch",
               "pertmp02.switch.ch",
               "pertmp04.switch.ch"
            ],
            "type" : "mesh"
         },
         "parameters" : {
            "protocol" : "tcp",
            "omit_interval" : "5",
            "duration" : "30",
            "interval" : "10800",
            "force_bidirectional" : "0",
            "ipv4_only" : "1",
            "tool" : "bwctl/iperf3",
            "random_start_percentage" : "10",
            "type" : "perfsonarbuoy/bwctl"
         },
         "description" : "IPv4 throughput matrix"
      },
      {
         "members" : {
            "members" : [
               "pertmp01.switch.ch",
               "pertmp06.switch.ch",
               "pertmp02.switch.ch",
               "pertmp04.switch.ch"
            ],
            "type" : "mesh"
         },
         "parameters" : {
            "protocol" : "udp",
            "max_ttl" : "64",
            "waittime" : "10",
            "pause" : "0",
            "force_bidirectional" : "0",
            "first_ttl" : "0",
            "ipv4_only" : "1",
            "timeout" : "60",
            "type" : "traceroute",
            "test_interval" : "1200",
            "packet_size" : "40"
         },
         "description" : "IPv4 bw-traceroute testing"
      },
      {
         "members" : {
            "members" : [
               "pertmp01.switch.ch",
               "pertmp06.switch.ch",
               "pertmp02.switch.ch",
               "pertmp04.switch.ch"
            ],
            "type" : "mesh"
         },
         "parameters" : {
            "force_bidirectional" : "0",
            "loss_threshold" : "10",
            "bucket_width" : "0.0001",
            "ipv4_only" : "1",
            "packet_padding" : "0",
            "sample_count" : "1200",
            "packet_interval" : "0.1",
            "type" : "perfsonarbuoy/owamp",
            "session_count" : "18000"
         },
         "description" : "IPv4 owd matrix"
      }
   ],
   "description" : "eduPERT Training Mesh"
}

[root@pertmp01 ~]# service perfsonar-meshconfig-agent restart
/etc/init.d/perfsonar-meshconfig-agent stop: perfSONAR MeshConfig Agent stopped
waiting...
/usr/lib/perfsonar/bin/perfsonar_meshconfig_agent --config=/etc/perfsonar/meshconfig-agent.conf --pidfile=/var/run/perfsonar-meshconfig-agent.pid --logger=/etc/perfsonar/meshconfig-agent-logger.conf --user=perfsonar --group=perfsonar
/etc/init.d/perfsonar-meshconfig-agent start: perfSONAR MeshConfig Agent started

[root@pertmp01 ~]# sed -n '1,/measurement_archive/p' /etc/perfsonar/meshconfig-agent-tasks.conf
<test>
    <parameters>
        tool   iperf3
        omit_interval   5
        type   bwctl
        duration   30
        force_ipv4   1
        send_only   1
    </parameters>
    target   pertmp06.switch.ch
    target   pertmp02.switch.ch
    local_address   pertmp04.switch.ch
    added_by_mesh   1
    description   IPv4 throughput matrix
    <schedule>
        random_start_percentage   10
        type   regular_intervals
        interval   10800
    </schedule>
</test>
<test>
    <parameters>
        tool   iperf3
        omit_interval   5
        type   bwctl
        duration   30
        force_ipv4   1
        send_only   1
    </parameters>
    target   pertmp06.switch.ch
    target   pertmp02.switch.ch
    local_address   pertmp01.switch.ch
    added_by_mesh   1
    description   IPv4 throughput matrix
    <schedule>
        random_start_percentage   10
        type   regular_intervals
        interval   10800
    </schedule>
</test>
<test>
    <parameters>
        packet_length   40
        packet_max_ttl   64
        type   bwtraceroute
        force_ipv4   1
    </parameters>
    target   pertmp06.switch.ch
    target   pertmp02.switch.ch
    local_address   pertmp04.switch.ch
    added_by_mesh   1
    description   IPv4 bw-traceroute testing
    <schedule>
        type   regular_intervals
        interval   1200
    </schedule>
</test>
<test>
    <parameters>
        packet_length   40
        packet_max_ttl   64
        type   bwtraceroute
        force_ipv4   1
    </parameters>
    target   pertmp06.switch.ch
    target   pertmp02.switch.ch
    local_address   pertmp01.switch.ch
    added_by_mesh   1
    description   IPv4 bw-traceroute testing
    <schedule>
        type   regular_intervals
        interval   1200
    </schedule>
</test>
<test>
    <parameters>
        resolution   120
        type   powstream
        force_ipv4   1
        send_only   1
    </parameters>
    target   pertmp06.switch.ch
    target   pertmp02.switch.ch
    local_address   pertmp04.switch.ch
    added_by_mesh   1
    **description   IPv4 owd matrix**
    <schedule>
        type   streaming
    </schedule>
</test>
<test>
    <parameters>
        resolution   120
        type   powstream
        force_ipv4   1
        send_only   1
    </parameters>
    target   pertmp06.switch.ch
    target   pertmp02.switch.ch
    local_address   pertmp01.switch.ch
    added_by_mesh   1
    **description   IPv4 owd matrix**
    <schedule>
        type   streaming
    </schedule>
</test>
<measurement_archive>
[root@pertmp01 ~]#

**Comment by igarny** [comment]
here are the meshconfig logs:
2016/10/18 16:37:27 (2818) INFO> perfsonar_meshconfig_agent:389 main:: - Added 4 new tasks, and deleted 4 old tasks
2016/10/18 16:54:27 (2818) INFO> perfsonar_meshconfig_agent:404 main:: - Configuration file change detected, refreshing records.
2016/10/18 16:55:26 (2818) WARN> perfsonar_meshconfig_agent:381 main:: - Problem deleting test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Until must be in the future.
CONTEXT:  SQL statement "UPDATE task SET enabled = FALSE WHERE uuid = task_uuid"
PL/pgSQL function api_task_disable(uuid,text) line 19 at SQL statement

2016/10/18 16:55:26 (2818) WARN> perfsonar_meshconfig_agent:381 main:: - Problem deleting test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Until must be in the future.
CONTEXT:  SQL statement "UPDATE task SET enabled = FALSE WHERE uuid = task_uuid"
PL/pgSQL function api_task_disable(uuid,text) line 19 at SQL statement

2016/10/18 16:55:26 (2818) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Unable to determine duration of test: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/../classes/tool/bwctliperf3/duration", line 26, in <module>
    duration += int(json['omit'])
ValueError: invalid literal for int() with base 10: 'PT5S'

2016/10/18 16:55:26 (2818) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Unable to determine duration of test: Traceback (most recent call last):
  File "/usr/libexec/pscheduler/commands/../classes/tool/bwctliperf3/duration", line 26, in <module>
    duration += int(json['omit'])
ValueError: invalid literal for int() with base 10: 'PT5S'

2016/10/18 16:55:26 (2818) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 500 Can't connect to pertmp04.switch.ch:443 (connect: Connection refused): 500 Can't connect to pertmp04.switch.ch:443 (connect: Connection refused)
2016/10/18 16:55:26 (2818) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 500 Can't connect to pertmp04.switch.ch:443 (connect: Connection refused): 500 Can't connect to pertmp04.switch.ch:443 (connect: Connection refused)
2016/10/18 16:55:26 (2818) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 403 FORBIDDEN: Task forbidden by limits:
Identified as everybody
Classified as everybody, default
Application: Defaults
    Group 1: Limit 'innocuous-tests' failed: Test type not in list
    Group 1: Limit 'rtt-default' failed: Test is not 'rtt'
    Group 1: Limit 'throughput-default' failed: Test is not 'throughput'
    Group 1: Want any, 0/3 passed, 3/3 failed: FAIL
    Group 1: Failed; stopping here.
    Application FAILS
Proposal does not meet limits
2016/10/18 16:55:26 (2818) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 403 FORBIDDEN: Task forbidden by limits:
Identified as everybody
Classified as everybody, default
Application: Defaults
    Group 1: Limit 'innocuous-tests' failed: Test type not in list
    Group 1: Limit 'rtt-default' failed: Test is not 'rtt'
    Group 1: Limit 'throughput-default' failed: Test is not 'throughput'
    Group 1: Want any, 0/3 passed, 3/3 failed: FAIL
    Group 1: Failed; stopping here.
    Application FAILS
Proposal does not meet limits
2016/10/18 16:55:26 (2818) INFO> perfsonar_meshconfig_agent:389 main:: - Added 4 new tasks, and deleted 4 old tasks

**Comment by arlake228** [comment]
Those last two tests aren't true duplicates. One has a local_address of pertmp04.switch.ch and another has a local address of pertmp01.switch.ch. Looking at your JSON file the meshconfig did the right thing since the Amsterdam host appears to have both those addresses and you requested both participate in that mesh.  

With regards to the other errors in the logs, those all look like know pscheduler issues as far as I can tell, some of which have already been fixed.

**Comment by igarny** [comment]
Thanks Andy and sorry for the time waster!
