### ISSUE TITLE
Generalize mesh-config to create pscheduler tasks and archivers

### ISSUE THREAD

**Issue by arlake228** [perfsonar/mesh-config#33]
I'd really like to make mesh-config much more general. I experimented with a few things in between 4.0 rc1 and 4.0rc2, but its clear we need some bigger changes to do this right out of scope for 4.0. I'd like mesh-config to evolve into a template language for building pscheduler tasks. The JSON for test definitions and archives should look like pscheduler tasks and archives respectively. We'll maybe throw in a few template variables where things change per host respectively. I'd really like to get to the point where we don't have to update mesh-config code every time we add a new test or update an existing one, and likewise for archivers.

**Comment by mfeit-internet2** [comment]
My take on this is that mesh-config might be the subject of the next pScheduler-style software shakeup.

All it needs is a name that begins with _pS_.  pScatter?  :-)

**Comment by igarny** [comment]
Hi,
my 50 cents here.
I assume Andy is referring to the test specification section in meshconfig. That certainly looks tempting to be directly transformed as a pscheduler task description.

still I believe pscheduler does not recognize or what is the process that translates these: 
force_bidirectional            0
random_start_percentage 10

There is quite an obvious risk or additional effort, that is going to be introduced with the meshconfig changes wrt MADDASH.  meshconfig provides a pretty good integration with MADDASH config. 
Do we know how many users are relying on this automation?

Regards,
Ivan

**Comment by arlake228** [comment]
Duplicates #77
