### ISSUE TITLE
Multiple instances of powstream started in parallel for a test couple

### ISSUE THREAD

**Issue by igarny** [perfsonar/mesh-config#40]
I have only 1 powstream schedule in tasks, but there are multiple processes started in parallel for each test couple.

[root@psps-test2-mgmt ~]# sed -n  '/powstream/,/default_parameters/p' /etc/perfsonar/meshconfig-agent-tasks.conf
        type   powstream
        force_ipv4   1
    </parameters>
    target   ps-test.ctc.grnoc.iu.edu
    target   perfsonar-dev5.grnoc.iu.edu
    target   ps-deb.es.net
    target   antg-dev.es.net
    target   antg-staging.es.net
    target   perfsonardev0.internet2.edu
    target   ma-dev2.bldc.grnoc.iu.edu
    target   perfsonar-dev.grnoc.iu.edu
    local_address   psps-test2-mgmt.rrze.uni-erlangen.de
    added_by_mesh   1
    description   OWAMP Test Between Testbeds
    <schedule>
        type   streaming
    </schedule>
</test>
<default_parameters>
    type   powstream
</default_parameters>

[root@psps-test2-mgmt ~]# ps ax | grep powstr | grep antg-dev.es.net | grep "\-4 \-t \-S"
11589 ?        S      0:03 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/bb33d90c-2221-4b99-be6b-cf692fd9be87 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
14507 ?        S      0:03 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/7fe3530c-69be-4e78-a831-ae30ca392550 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
28873 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/7fe3530c-69be-4e78-a831-ae30ca392550 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
28891 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/bb33d90c-2221-4b99-be6b-cf692fd9be87 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
30299 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/7fe3530c-69be-4e78-a831-ae30ca392550 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
30455 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/bb33d90c-2221-4b99-be6b-cf692fd9be87 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -t -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861

[root@psps-test2-mgmt ~]# ps ax | grep powstr | grep antg-dev.es.net | grep "\-4 \-S"
12286 ?        S      0:06 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/b6cea711-25fe-4f80-9848-d02cd697a2c0 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
14380 ?        S      0:07 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/003e2a90-cdf8-4dd8-bb39-97945366b53d -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
30457 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/003e2a90-cdf8-4dd8-bb39-97945366b53d -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
30899 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/b6cea711-25fe-4f80-9848-d02cd697a2c0 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
32380 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/b6cea711-25fe-4f80-9848-d02cd697a2c0 -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861
32635 ?        Ss     0:00 /usr/bin/powstream -p -d /var/lib/pscheduler/tool/powstream/003e2a90-cdf8-4dd8-bb39-97945366b53d -s 0 -P 8760-9960 -c 600 -i 0.1 -4 -S psps-test2-mgmt.rrze.uni-erlangen.de [antg-dev.es.net]:861

Software environment:
perfsonar-meshconfig-agent.noarch   4.0-0.6.rc2.el6           @Internet2-staging
perfsonar-meshconfig-shared.noarch  4.0-0.6.rc2.el6           @Internet2-staging

pscheduler-account.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-archiver-bitbucket.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-archiver-esmond.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-archiver-failer.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-archiver-syslog.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-bundle-full.noarch 1.0-1.15.rc2.el6 @Internet2-staging
pscheduler-core.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-rpm.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-server.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-test-idle.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-test-idlebg.noarch 1.0-0.15.rc2.el6 @Internet2-staging
pscheduler-test-idleex.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-test-latency.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-test-latencybg.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-test-rtt.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-test-simplestream.noarch 1.0-0.17.rc2.el6 @Internet2-staging
pscheduler-test-throughput.noarch 1.0-0.17.rc2.el6 @Internet2-staging

**Comment by arlake228** [comment]
I saw this too this morning on antg-staging. I think it might be an issue with the pscheduler powstream tool. In my case the old powstreams that had expired were not killed. strace showed the powstream run command stuck on a select somewhere: 

```
[rootal@antg-staging ~]# strace -p 129395
Process 129395 attached
select(0, NULL, NULL, NULL, {53, 741272}
```

Need to look into where and why it is getting stuck.

**Comment by igarny** [comment]
could be related to https://github.com/perfsonar/pscheduler/issues/238

**Comment by arlake228** [comment]
Looks like process counts have been stable the past couple days, so closing.
