### ISSUE TITLE
failures (connect: No route to host) in meshconfig-agent.log

### ISSUE THREAD

**Issue by igarny** [perfsonar/mesh-config#43]
Hi Andy,

The message below repeats itself multiple times in my logs of meshconfig-agent:
`
2016/12/16 17:24:45 (27458) WARN> perfsonar_meshconfig_agent:381 main:: - Problem adding test, continuing with rest of config: 500 Can't connect to ps-owdtst.rrze.uni-erlangen.de:443 (connect: No route to host): 500 Can't connect to ps-owdtst.rrze.uni-erlangen.de:443 (connect: No route to host)
`
There might be some FW blocking 443 on the specified interface, but I really doubt. Check the Test Mesh MaDDash how others interact.
Still in either case initiation of pscheduler tasks should not be a problem. Meshconfig has already identified that ps-owdtst is a local interface (from agent-tasks.conf). Meaning the service is probably trying to post the tasks through the external IP, instead of directly to localhost.

`
<test>
    <parameters>

        type   powstream
        force_ipv4   1
    </parameters>
    target   perfsonar-dev5.grnoc.iu.edu
    target   ps-deb.es.net
    target   antg-dev.es.net
    target   antg-staging.es.net
    target   perfsonardev0.internet2.edu
    target   ma-dev2.bldc.grnoc.iu.edu
    target   perfsonar-dev.grnoc.iu.edu
    target   ps-deb-2.es.net
    target   perfsonar-lab-vm.ilab.umnet.umich.edu
    target   ps-4-0.qalab.geant.net
    target   pstest.geant.carnet.hr
    local_address   ps-owdtst.rrze.uni-erlangen.de
    added_by_mesh   1
    description   OWAMP Test Between Testbeds
    <schedule>
        type   streaming
    </schedule>
</test>
`

**Comment by igarny** [comment]
Most likely the problem is only limited to the powstream tasks, since: 

[root@psps-test2-mgmt ~]# pscheduler schedule | grep latency
[root@psps-test2-mgmt ~]# pscheduler schedule | grep trace
trace --dest perfsonar-lab-vm.ilab.umnet.umich.edu --ip-version 4 --source ps-
  owdtst.rrze.uni-erlangen.de (Run with tool 'tracepath')
trace --dest ps-4-0.qalab.geant.net --ip-version 4 --source ps-owdtst.rrze.uni-
  erlangen.de (Run with tool 'tracepath')
......
[root@psps-test2-mgmt ~]# pscheduler schedule | grep -c trace
62

**Comment by igarny** [comment]
This one demonstrates that there is no problem with communication over https through ps-owdtst interface.

[root@psps-test2-mgmt ~]# curl -k https://**ps-owdtst**.rrze.uni-erlangen.de/pscheduler/tasks/9e41f948-bda7-46f2-99e1-161d047e62e4
{"reference": {"created-by": {"user-agent": "perfsonar-meshconfig", "uuid": "e689ed7e-ab5b-4726-b305-8ed8d46e4f7a", "address": "perfsonar-dev.grnoc.iu.edu"}, "description": "BWCTL 4H TCP Test Between Testbeds"}, "schedule": {"start": "2016-12-19T09:39:41Z", "repeat": "PT14400S", "randslip": 0.25, "until": "2016-12-20T09:39:41Z", "slip": "PT14400S"}, "tool": "iperf3", "archives": [{"archiver": "esmond", "data": {"url": "http://localhost/esmond/perfsonar/archive/", "retry-policy": [{"attempts": 5, "wait": "PT60S"}, {"attempts": 3, "wait": "PT5M"}, {"attempts": 24, "wait": "PT60M"}], "summaries": [{"summary-type": "average", "summary-window": 86400, "event-type": "throughput"}], "measurement-agent": "perfsonar-dev.grnoc.iu.edu"}}, {"archiver": "esmond", "data": {"url": "http://ps-test.ctc.grnoc.iu.edu/esmond/perfsonar/archive/", "retry-policy": [{"attempts": 5, "wait": "PT60S"}, {"attempts": 3, "wait": "PT5M"}, {"attempts": 24, "wait": "PT60M"}], "summaries": [{"summary-type": "average", "summary-window": 86400, "event-type": "throughput"}], "measurement-agent": "perfsonar-dev.grnoc.iu.edu"}}], "test": {"type": "throughput", "spec": {"dest": "psps-test2-mgmt.rrze.uni-erlangen.de", "source": "perfsonar-dev.grnoc.iu.edu", "ip-version": 4, "duration": "PT20S", "parallel": 1, "schema": 1}}, "tools": ["bwctliperf3", "iperf3"], "schema": 1}

**Comment by igarny** [comment]
could be related to: https://github.com/perfsonar/pscheduler/issues/249

**Comment by arlake228** [comment]
What do you get  if you run `curl -k "https://\[2001:638:a000:3502::52\]/pscheduler/tools"`? Does it return or do you get a connection error? Also, can you verify that the owamp interface on your host indeed has IPv6 address 2001:638:a000:3502::52 (which is what is in DNS)? 

I have a theory this might be IPv6 -related, but its manifesting itself a bit differently than the case I fixed earlier in the week where perl does not properly do IPv4 fallback. 

For reference, from an esnet host I get the following, and the ipv6 case seems to map to the error message you are seeing in your logs: 

IPv4:
```
[rootal@antg-staging ~]# curl -k "https://131.188.81.82/pscheduler/tools"
["https://131.188.81.82/pscheduler/tools/bwctliperf2", "https://131.188.81.82/pscheduler/tools/bwctlping", "https://131.188.81.82/pscheduler/tools/iperf2", "https://131.188.81.82/pscheduler/tools/iperf3", "https://131.188.81.82/pscheduler/tools/sleepbg", "https://131.188.81.82/pscheduler/tools/sleep", "https://131.188.81.82/pscheduler/tools/tracepath", "https://131.188.81.82/pscheduler/tools/powstream", "https://131.188.81.82/pscheduler/tools/traceroute", "https://131.188.81.82/pscheduler/tools/simplestreamer", "https://131.188.81.82/pscheduler/tools/bwctliperf3", "https://131.188.81.82/pscheduler/tools/snooze", "https://131.188.81.82/pscheduler/tools/ping", "https://131.188.81.82/pscheduler/tools/owping", "https://131.188.81.82/pscheduler/tools/bwctltracepath", "https://131.188.81.82/pscheduler/tools/paris-traceroute", "https://131.188.81.82/pscheduler/tools/bwctltraceroute"]
```

IPv6:
```
[rootal@antg-staging ~]# curl -k "https://\[2001:638:a000:3502::52\]/pscheduler/tools"
curl: (7) Failed connect to 2001:638:a000:3502::52:443; No route to host
```

**Comment by igarny** [comment]
Not sure what brought the improvement, but there is one. You are right there is an IPv6 address assigned, which had not been applied. I have also updated pS.

**Comment by arlake228** [comment]
Looks like we corrected this particular issue. Closing.
