### ISSUE TITLE
Reverse tests try to right to ma on localhost

### ISSUE THREAD

**Issue by arlake228** [perfsonar/mesh-config#46]
Let's say you have two hosts A and B. If host A asks for a throughput, ping, or traceroute test from B to A, it has to send a request to host B, since it will be the lead. Host B will also be responsible for archiving the result since it is the lead (and in the case of ping and traceroute it will be the only participant). The problem is when host A's meshconfig-agent-tasks.conf file has "localhost" in it as the MA. It asks host B to write to localhost, but that is incorrect, and what you are seeing in this case. I am working on fixing this so Host A plugs in a public address when it sees something like localhost. My plan is to make my best quess at the public address when nothing is specified, but also add a public_url to the measurement_archive block for multi-interface cases since its almost assured the best guess will be wrong in a lot of instances so admins will need a way to set it correctly.

**Comment by igarny** [comment]
Please also consider the    lsregistrationdaemon.conf     and the section, which specifies the interface of the MA before doing a best guess.

**Comment by arlake228** [comment]
Not going to look in lsregistartiondaemon.conf. Don't really like the idea of digging in other packages config files. There is a public_url option that can now be set for measurement_archive blocks where it can be explicitly set if for whatever reason someone wants to leave the loopback or private address in the main field.
