### ISSUE TITLE
add support for new iperf3 option 'fq-rate'

### ISSUE THREAD

**Issue by bltierney** [perfsonar/mesh-config#48]
iperf3 has the following new option that we need to be able to configure via for a test mesh:
 --fq-rate N

Note that this is separate from --bandwidth, and works for both TCP and UDP.

Therefore we need a new test parameter directive added to the mesh config file.
'fq-rate' is probably the best name for this.

**Comment by arlake228** [comment]
is there also a pscheduler issue for this (didn't see it just now when i looked)? there should probably be two issues: 1) assigned to Dan to get in pscheduler and 2) this one but assigned to me to put in mesh-config.

**Comment by bltierney** [comment]
doing that now.
