### ISSUE TITLE
Debian: meshconfig-agent-tasks.conf shouldn't be marked as config file

### ISSUE THREAD

**Issue by laeti-tia** [perfsonar/mesh-config#50]
During apt-get upgrade process, the `/etc/perfsonar/meshconfig-agent-tasks.conf` file is flagged as being modified since installation and the upgrade process stop to ask the admin for confirmation of what to do (keep the changed file or take the update file from the package). The file is managed by the meshconfig-agent which is directly modifying it.

I think this file shouldn't be marked as config file otherwise auto-update will fail everytime we ship a new version of this file in the package.

**Comment by vvidic** [comment]
Workaround for handling ``meshconfig-agent-tasks.conf`` added to jessie an wheezy branches.

**Comment by laeti-tia** [comment]
Thanks, that's a nice change!
