### ISSUE TITLE
agent trying to delete/disable tasks that it added, but cannot find them

### ISSUE THREAD

**Issue by somedatapacket** [perfsonar/mesh-config#55]
How does perfsonar_meshconfig_agent determine which pscheduler tests to delete, and when? We are seeing a number of errors like this: perfsonar_meshconfig_agent:381 main:: - Problem deleting test, continuing with rest of config: 500 INTERNAL SERVER ERROR: Task not found while disabling task f5162b78-5ed9-47e1-87b1-cccd0c51a83a
CONTEXT:  PL/pgSQL function api_task_disable(uuid,text) line 12 at RAISE.

**Comment by arlake228** [comment]
Need to review whether still an issue.

**Comment by arlake228** [comment]
Closing since applies to mesh-config. can open new issue if re-appears in psconfig
