### ISSUE TITLE
toolkit only schedules iperf3 results in 1 direction

### ISSUE THREAD

**Issue by bltierney** [perfsonar/mesh-config#56]
The following was observed on nettest.lbl.gov toolkit.

'pscheduler schedule ' command only reports tests being scheduled to test-pt1.es.net, and not tests  in the other direction.

To check this, you can run:
	pscheduler schedule --filter-test=throughput -PT1H > /tmp/sched.out
	grep -2 test-pt1 /tmp/sched.out | more

**Comment by apertome** [comment]
When is this being built/released? In nightly?
