### ISSUE TITLE
Add &expanded to task list queries done by mesh-config so don't have to query individual tasks

### ISSUE THREAD

**Issue by arlake228** [perfsonar/mesh-config#58]
There is already an &expanded option that gives the task information, which would save from having to query every task individually like mesh-config does now. It does not yet support the detail option though, but @mfeit-internet2 said that won;t be too hard to add. Once e have that, we should update the mesh-config to use it.

**Comment by mfeit-internet2** [comment]
Note to self:  Need to pull the code that generates the details from `/tasks/get/xxx` into a function and call it from `/tasks/get` when `details` and `expanded` are set.

**Comment by arlake228** [comment]
Moving as a stretch goal for final since lot more high priority stuff on plate
