### ISSUE TITLE
Create additional pSConfig unit tests

### ISSUE THREAD

**Issue by apertome** [perfsonar/mesh-config#68]
- [ ] Coverage for most/all basic functions
- [ ] Test various tools/tests/parameters
- [ ] Test output format/content is correct
- [ ] Test with various example configs

**Comment by apertome** [comment]
I'm not familiar enough with the MeshConfig to get too specific here -- so, please add more details about what tests are needed.

**Comment by arlake228** [comment]
Closing as I have been writing these as I go. I will continue to do so and will create specific issues as needed for specific unit tests.
