### ISSUE TITLE
Write parsing libraries for new JSON schema

### ISSUE THREAD

**Issue by arlake228** [perfsonar/mesh-config#74]
Once we  have the JSON schema from #73, we need to write a parsing library to consume it.

**Comment by arlake228** [comment]
Code in perl-shared psconfig branch. Will merge into master post-4.0.2. There is an RPM libperfsonar-psconfig-perl. It requires a new perl-JSON-Validator package that is already in nightly (and perl-JSON-Validator also requires perl-JSON-Mojolicious which in turn required perl-EV which are also in nightly/minor packages).

**Comment by vvidic** [comment]
Please ping when psconfig branch is merged into master so I can work on the Debian packages.
