### ISSUE TITLE
Create tool that reports statistics on number of tests run per host

### ISSUE THREAD

**Issue by arlake228** [perfsonar/mesh-config#9]
It would be nice to have a tool that outputs statistics on how many tests a host is running given all the meshes in which it participates. This would especially useful for determining if a host is in danger of port exhaustion or similar.

**Comment by laeti-tia** [comment]
@arlake228 Andy, how and where do you see the output of this tool?  Would it be a CLI tool run by cron?  Or giving output as part of the toolkit web-interface?  Or something that runs on the central server?

**Comment by HakanCalimFau** [comment]
OK I am checking this. Will add some comments later.

**Comment by HakanCalimFau** [comment]
The idea is to collect all the JSON mesh config files which are defined in:
/etc/perfsonar/meshconfig-agent.conf

Select all the hosts which are running measurement with the host where the statistics tool is executed. I suggest to call this tool get_meshconfig_stats. The statistic can have following format:
mesh_config_statistics 
  [  
    local_interfaces [+]
      [
        adresses [+]
         [
           tool [+]
            [
              host_endpoint [+]
               [ 
                 address
               ]
            ]
         ] 
...

What do you think?

**Comment by arlake228** [comment]
I'm a little confused by the notation. What will you be reporting for each of those items? What I would ultimately like is:
- The number of tests each host is running categorized by type (i.e. iperf, ping, owamp, traceroute, etc)
- The number of each type of test on each interface of the host
- The percentage of the time a host will be running throughput tests

There might be others but those are off the top of my head. I think some of that may be in what you have but it's hard for me to tell. We ultimately want a tool to help people know if they are overwhelming any hosts with the mesh the way they have it setup.

**Comment by laeti-tia** [comment]
Andy, do you want that on the central mesh server or on each of the participating nodes?  What if a node participates to multiple meshes?

**Comment by arlake228** [comment]
I want this to read the central mesh JSON file. E.g. This file: http://ps-west.es.net:8096/esnet-mesh_config.json

I want to point it at the JSON and get statistics for everything in the mesh at once. i.e. I do NOT want to have to log-in to each node and run this script and get info about just that host.I want the ability to analyze a mesh as a whole and use that information to make decision about rebalancing my mesh, etc. if needed.

**Comment by HakanCalimFau** [comment]
[esnet-mesh_config-statistic.txt](https://github.com/perfsonar/mesh-config/files/244805/esnet-mesh_config-statistic.txt)

**Comment by HakanCalimFau** [comment]
I have uploaded a statistic output from the esnet mesh config file what Andy had mentioned above. Not sure if the output is correct. I have simple tests which runs successfully. Andy what do you think about the output.

**Comment by arlake228** [comment]
@HakanCalimFau: Looks like a good start! A few things of note:
- I actually think each column needs three counts
1. The number of tests the host is initiating (i.e. more or less what you have now). By "initiating" I mean if I were to SSH into the host and look at the process list, would I see a client parent process associated with that tests? It has nothing to do with who is the source and who is the destination (I only mention this because the terminology can be confusing)
2. The number of tests a remote side initiates but is running against the current host
3. The total of 1 and 2
- A couple things to keep in mind when doing the counts:
1. If a host object of the remote side of the test has no_agent set, then that host does not actually initiate any tests, it only has tests initiated to it. 
2.  If the test_specification is "force_bidirectional 1" you need to double the amount of tests initiated. That means that if you have a mesh with force_bidirectional and two hosts (call them host A and host B) and  both do not set no_agent, what you are counting as 1 test now is actually 4 tests total (2 initiated by host A and 2 initiated by host B).
- Another stat it would be nice to report for the BWCTL tests is the percentage of time tests are being run. This will require looking at the interval and duration parameters in addition to the test counts.

Hopefully that's helpful and let me know if you have any questions.

**Comment by HakanCalimFau** [comment]
To !:
Actually I am interating over all hosts and count the number of tests for all addresses. At the moment I do this also for hoss which doesn't initiating tests. Is it enouh when I do it for hosts where no_agent is not set?

To 2:
This I don't understand. When a host address has tests with 5 hosts. Then it should be also reported the number of tests which each host ist running against the host address? This should be shown as a total number?

**Comment by arlake228** [comment]
To 1:

If you break up the counts into three values like I suggest, the no_agent hosts will be clearer I think. The number of tests initiated will always be 0, the number of tests initiated remotely will be essentially the number you have now and the total will also be the number you have now.

To 2:
Correct. If 5 hosts are initiating tests to the current host I want that number reported and then I also want the total count when added with the hosts initiated. The reason for this is that regardless of who initiates it, it's still on the scheduler and thus makes the host busier, and a primary motivation for using this tool is to see how busy a host is with tests.
